server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/web03_chat_room?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379

#整合mybatis别名
mybatis:
  type-aliases-package: com.community.community.pojo
  mapper-locations: classpath:mapper/*.xml

